config/routes.rb
HemlockFrontend::Application.routes.draw do
  root :to => 'searches#search'  
  authenticated :user do
    root :to => 'searches#search'
  end
  
  devise_scope :user do 
    root :to => "devise/sessions#new"
  end

  devise_for :users

  match 'about', :controller => 'static_pages', :action => 'about', :as => :about
  match 'search', :controller => 'searches', :action => 'search', :as => :search
  match 'searches/ajax_load_results', :controller => 'searches'
  
  namespace :api do
    devise_for :users, :controllers => {sessions:'sessions'} # custom controller for API token access
  end
  
  namespace :admin do
    resources :hemlock_tenants, :hemlock_systems, :hemlock_users, :hemlock_roles
  end

  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = HemlockUser.all
    puts @users.inspect
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Registered</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <%= user.inspect %>
    <tr>
      <td><%= link_to user.name, admin_hemlock_user_path(user.uuid) %></td>
      <td><%= user.email %></td>
      <td><%= user.created.to_date %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>

<p>
  User: <%= @user.name %>
  <%= link_to("Delete user", user_path(@user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless @user == current_user %>
</p>
<p>Email: <%= @user.email if @user.email %></p>