config/routes.rb
HemlockFrontend::Application.routes.draw do
  root :to => 'searches#search'  
  authenticated :user do
    root :to => 'searches#search'
  end
  
  devise_scope :user do 
    root :to => "devise/sessions#new"
  end

  devise_for :users

  match 'about', :controller => 'static_pages', :action => 'about', :as => :about
  match 'search', :controller => 'searches', :action => 'search', :as => :search
  match 'searches/ajax_load_results', :controller => 'searches'
  
  namespace :api do
    devise_for :users, :controllers => {sessions:'sessions'} # custom controller for API token access
  end
  
  namespace :admin do
    resources :hemlock_tenants, :hemlock_systems, :hemlock_users, :hemlock_roles
  end

  resources :users
end

app/models/hemlock_role.rb
class HemlockRole < HemlockModel


  ################################################
  # class methods
  ################################################  
  def initialize(args=nil)
    super
  end


  ################################################
  # class methods
  ################################################ 
  # broadcast instance methods
  def respond_to?(method_name, include_private = false)
    ["users"].include? (method_name.to_s) || super
  end
  
end

app/controllers/admin/hemlock_roles_controller.rb
class Admin::HemlockRolesController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @hemlock_roles = HemlockRole.all
  end
  
  def show
    @hemlock_role = HemlockRole.find(params[:id])
    @hemlock_users = @hemlock_role.users
  end

end

app/views/admin/hemlock_roles/_index.html.erb
<h3>Roles</h3>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <table class="table table-condensed datatable">
        <thead>
          <tr>
            <th>Name</th>
            <th>Username</th>
          </tr>
        </thead>
        <tbody>
          <% unless @hemlock_roles.nil? %>
            <% @hemlock_roles.each do |role| %>
              <tr>
                <td><%= link_to role.name, admin_hemlock_role_path(role.uuid) if role.uuid %></td>       
                <td><%= role.created.to_date if role.created %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/hemlock_roles/index.html.erb
<%= render :partial => "index" %>

app/views/admin/hemlock_roles/show.html.erb
<h2>Hemlock Role</h2>
<p>ID: <%= @hemlock_role.id %></p>
<p>UUID: <%= @hemlock_role.uuid %></p>
<p>Name: <%= @hemlock_role.name %></p>
<p>Created: <%= @hemlock_role.created.to_date %></p>

<%= render :partial => "admin/hemlock_users/index" %>