config/routes.rb
HemlockFrontend::Application.routes.draw do
  root :to => 'searches#search'  
  authenticated :user do
    root :to => 'searches#search'
  end
  
  devise_scope :user do 
    root :to => "devise/sessions#new"
  end

  devise_for :users

  match 'about', :controller => 'static_pages', :action => 'about', :as => :about
  match 'search', :controller => 'searches', :action => 'search', :as => :search
  match 'searches/ajax_load_results', :controller => 'searches'
  
  namespace :api do
    devise_for :users, :controllers => {sessions:'sessions'} # custom controller for API token access
  end
  
  namespace :admin do
    resources :hemlock_tenants, :hemlock_systems, :hemlock_users, :hemlock_roles
  end

  resources :users
end

app/models/hemlock_system.rb
class HemlockSystem < HemlockModel
# class variables
attr_accessor :data_type, :description, :endpoint, :hostname, :port, :remote_uri, :poc_name, :poc_email, :remote, :updated_data

  ################################################
  # class methods
  ################################################  
  def initialize(args=nil)
    super
    self.port = self.port.to_i unless self.port.nil?
    self.remote = self.remote.to_i unless self.remote.nil?
  end
   
   
  ################################################
  # class methods
  ################################################ 
  # broadcast instance methods
  def respond_to?(method_name, include_private = false)
    ["tenants"].include? (method_name.to_s) || super
  end
end

app/controllers/admin/hemlock_systems_controller.rb
class Admin::HemlockSystemsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @hemlock_systems = HemlockSystem.all
  end
  
  def show
    @hemlock_system = HemlockSystem.find(params[:id])
    @hemlock_tenants = @hemlock_system.tenants
  end

end

app/views/admin/hemlock_systems/_index.html.erb
<h3>Systems</h3>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <table class="datatable table table-condensed">
        <thead>
          <tr>
            <th>System</th>
            <th>Data Type</th>
            <th>Description</th>
            <th>POC</th>
          </tr>
        </thead>
        <tbody>
        <%# :data_type, :description, :endpoint, :hostname, :port, :remote_uri, :poc_name, :poc_email, :remote, :updated_data %>
        <% unless @hemlock_systems.nil? %>
          <% @hemlock_systems.each do |system| %>
            <tr>
              <td><%= link_to system.name, admin_hemlock_system_path(system.uuid) if system.uuid %></td>
              <td><%= system.data_type if system.data_type %></td>
              <td><%= truncate(system.description) if system.description%></td>
              <td><%= "#{system.poc_name} (#{system.poc_email})"%></td>
            </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/hemlock_systems/index.html.erb
<%= render :partial => "index" %>

app/views/admin/hemlock_systems/show.html.erb
<h2>Hemlock System</h2>
<p>ID: <%= @hemlock_system.id %></p>
<p>UUID: <%= @hemlock_system.uuid %></p>
<p>Data Type: <%= @hemlock_system.data_type %></p>
<p>POC: <%= "#{@hemlock_system.poc_name} (#{@hemlock_system.poc_email})" %></p>
<p>Description: <%= @hemlock_system.description %></p>

<%= render :partial => "admin/hemlock_tenants/index" %>