config/routes.rb
HemlockFrontend::Application.routes.draw do
  root :to => 'searches#search'  
  authenticated :user do
    root :to => 'searches#search'
  end
  
  devise_scope :user do 
    root :to => "devise/sessions#new"
  end

  devise_for :users

  match 'about', :controller => 'static_pages', :action => 'about', :as => :about
  match 'search', :controller => 'searches', :action => 'search', :as => :search
  match 'searches/ajax_load_results', :controller => 'searches'
  
  namespace :api do
    devise_for :users, :controllers => {sessions:'sessions'} # custom controller for API token access
  end
  
  namespace :admin do
    resources :hemlock_tenants, :hemlock_systems, :hemlock_users, :hemlock_roles
  end

  resources :users
end

app/views/layouts/_navigation.html.erb
<% class_users = (controller.controller_name == "users") ? "active hidden-tablet hidden-phone" : "hidden-tablet hidden-phone" %>
<%= link_to image_tag("logo.png", :class => 'logo'), root_path, :class => 'brand'  %>
<ul class="nav">

  <% if user_signed_in? %>


  <% else %>

  <% end %>
</ul>

<ul class="nav" style="float:right">
  <li class="hidden-tablet hidden-phone"><div class="logo-secondary-<%= ENV['HOST_HEMLOCK_DBTYPE'] %>"></div></li>
  <li>
  <%= link_to button_icon('icon-globe', 'About'), about_path  %>
  </li>
  <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
      <li><%= link_to button_icon('icon-user', 'Users'), admin_hemlock_users_path, :class => class_users %></li>
    <% end %>
      <li><%= link_to button_icon('icon-user', 'Edit account'), edit_user_registration_path %></li>
      <li><%= link_to button_icon('icon-signout','Logout'), destroy_user_session_path, :method=>'delete'  %></li>
  <% else %>
    <li><%= link_to button_icon('icon-bolt', 'Sign up'), new_user_registration_path  %></li>
    <li><%= link_to button_icon('icon-user', 'Login'), new_user_session_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Lab41 Hemlock" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Prelaunch Signup" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application","http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/smoothness/jquery-ui.css" %>

    <%= yield(:head) %>
  </head>
  <body class="body-<%= ENV['HOST_HEMLOCK_DBTYPE'] %>">
    <div id="canvas">
      <header class="navbar navbar-fixed-top">
        <nav class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </nav>
      </header>
      <div class="disclaimer">
        <%= disclaimer %>
      </div>
      <div id="main" role="main">
        <div class="container">
          <div class="content">
             <div class="row">
              <div class="span12">
                <div id="content">
                  <%= render 'layouts/messages' %>
                  <%= yield %>              
                </div>
              </div>
            </div>
            <footer>
            </footer>
          </div>
        </div> <!--! end of .container -->
      </div> <!--! end of #main -->
    </div> <!--! end of #canvas -->
  </body>
</html>